# 字句要素
KEYWORD: str        = "keyword"
SYMBOL: str         = "symbol"
INDETIFIER: str     = "identifier"
INT_CONST: str      = "integerConstant"
STRING_CONST: str   = "stringConstant"


# キーワード
CLASS: str          = "class"
METHOD: str         = "constructor"
FUNCTION: str       = "function"
CONSTRUCTOR: str    = "constructor"
INT: str            = "int"
BOOLEAN: str        = "boolean"
CHAR: str           = "char"
VOID: str           = "void"
VAR: str            = "var"
STATIC: str         = "static"
FIELD: str          = "field"
LET: str            = "let"
DO: str             = "do"
ELSE: str           = "else"
WHILE: str          = "while"
RETURN: str         = "return"
TRUE: str           = "true"
FALSE: str          = "false"
NULL: str           = "null"
THIS: str           = "this"